const fechas =
{
  fecha_1: {
    nombre: 'Fecha 1',
    partido_1: { equipo_1: 'Albatros', equipo_2: 'Welcome', id: 'partido_1'},
    partido_2: { equipo_1: 'Layva', equipo_2: 'Reducto', id: 'partido_2'},
    partido_3: { equipo_1: 'Atenas', equipo_2: 'Bohemios', id: 'partido_3'},
    partido_4: { equipo_1: 'Capurro', equipo_2: 'Yale', id: 'partido_4'},
    partido_5: { equipo_1: 'Paysandu', equipo_2: 'Marne', id: 'partido_5'},
    partido_6: { equipo_1: 'Juventud', equipo_2: 'Montevideo', id: 'partido_6'},
  },
  fecha_2: {
    nombre: 'Fecha 2',
    partido_1: { equipo_1: 'Montevideo', equipo_2: 'Albatros', id: 'partido_1'},
    partido_2: { equipo_1: 'Marne', equipo_2: 'Juventud', id: 'partido_2'},
    partido_3: { equipo_1: 'Yale', equipo_2: 'Paysandu', id: 'partido_3'},
    partido_4: { equipo_1: 'Bohemios', equipo_2: 'Capurro', id: 'partido_4'},
    partido_5: { equipo_1: 'Reducto', equipo_2: 'Atenas', id: 'partido_5'},
    partido_6: { equipo_1: 'Auriblanco', equipo_2: 'Layva', id: 'partido_6'},
  },
  fecha_3: {
      nombre: 'Fecha 3',
      partido_1: { equipo_1: 'Albatros', equipo_2: 'Marne', id: 'partido_1'},
      partido_2: { equipo_1: 'Atenas', equipo_2: 'Auriblanco', id: 'partido_2'},
      partido_3: { equipo_1: 'Capurro', equipo_2: 'Reducto', id: 'partido_3'},
      partido_4: { equipo_1: 'Paysandu', equipo_2: 'Bohemios', id: 'partido_4'},
      partido_5: { equipo_1: 'Juventud', equipo_2: 'Yale', id: 'partido_5'},
      partido_6: { equipo_1: 'Welcome', equipo_2: 'Montevideo', id: 'partido_6'},
    },
  fecha_4: {
      nombre: 'Fecha 4',
      partido_1: { equipo_1: 'Yale', equipo_2: 'Albatros', id: 'partido_1'},
      partido_2: { equipo_1: 'Marne', equipo_2: 'Welcome', id: 'partido_2'},
      partido_3: { equipo_1: 'Bohemios', equipo_2: 'Juventud', id: 'partido_3'},
      partido_4: { equipo_1: 'Reducto', equipo_2: 'Paysandu', id: 'partido_4'},
      partido_5: { equipo_1: 'Auriblanco', equipo_2: 'Capurro', id: 'partido_5'},
      partido_6: { equipo_1: 'Layva', equipo_2: 'Atenas', id: 'partido_6'},
    },
  fecha_5: {
      nombre: 'Fecha 5',
      partido_1: { equipo_1: 'Albatros', equipo_2: 'Bohemios', id: 'partido_1'},
      partido_2: { equipo_1: 'Capurro', equipo_2: 'Layva', id: 'partido_2'},
      partido_3: { equipo_1: 'Paysandu', equipo_2: 'Auriblanco', id: 'partido_3'},
      partido_4: { equipo_1: 'Juventud', equipo_2: 'Reducto', id: 'partido_4'},
      partido_5: { equipo_1: 'Welcome', equipo_2: 'Yale', id: 'partido_5'},
      partido_6: { equipo_1: 'Montevideo', equipo_2: 'Marne', id: 'partido_6'},
    },
  fecha_6: {
      nombre: 'Fecha 6',
      partido_1: { equipo_1: 'Reducto', equipo_2: 'Albatros', id: 'partido_1'},
      partido_2: { equipo_1: 'Yale', equipo_2: 'Montevideo', id: 'partido_2'},
      partido_3: { equipo_1: 'Bohemios', equipo_2: 'Welcome', id: 'partido_3'},
      partido_4: { equipo_1: 'Auriblanco', equipo_2: 'Juventud', id: 'partido_4'},
      partido_5: { equipo_1: 'Layva', equipo_2: 'Paysandu', id: 'partido_5'},
      partido_6: { equipo_1: 'Atenas', equipo_2: 'Capurro', id: 'partido_6'},
    },
  fecha_7: {
      nombre: 'Fecha 7',
      partido_1: { equipo_1: 'Albatros', equipo_2: 'Auriblanco', id: 'partido_1'},
      partido_2: { equipo_1: 'Paysandu', equipo_2: 'Atenas', id: 'partido_2'},
      partido_3: { equipo_1: 'Juventud', equipo_2: 'Layva', id: 'partido_3'},
      partido_4: { equipo_1: 'Welcome', equipo_2: 'Reducto', id: 'partido_4'},
      partido_5: { equipo_1: 'Montevideo', equipo_2: 'Bohemios', id: 'partido_5'},
      partido_6: { equipo_1: 'Marne', equipo_2: 'Yale', id: 'partido_6'},
    },
  fecha_8: {
      nombre: 'Fecha 8',
      partido_1: { equipo_1: 'Layva', equipo_2: 'Albatros', id: 'partido_1'},
      partido_2: { equipo_1: 'Bohemios', equipo_2: 'Marne', id: 'partido_2'},
      partido_3: { equipo_1: 'Reducto', equipo_2: 'Montevideo', id: 'partido_3'},
      partido_4: { equipo_1: 'Auriblanco', equipo_2: 'Welcome', id: 'partido_4'},
      partido_5: { equipo_1: 'Atenas', equipo_2: 'Juventud', id: 'partido_5'},
      partido_6: { equipo_1: 'Capurro', equipo_2: 'Paysandu', id: 'partido_6'},
    },
  fecha_9: {
      nombre: 'Fecha 9',
      partido_1: { equipo_1: 'Albatros', equipo_2: 'Atenas', id: 'partido_1'},
      partido_2: { equipo_1: 'Juventud', equipo_2: 'Capurro', id: 'partido_2'},
      partido_3: { equipo_1: 'Welcome', equipo_2: 'Layva', id: 'partido_3'},
      partido_4: { equipo_1: 'Montevideo', equipo_2: 'Auriblanco', id: 'partido_4'},
      partido_5: { equipo_1: 'Marne', equipo_2: 'Reducto', id: 'partido_5'},
      partido_6: { equipo_1: 'Yale', equipo_2: 'Bohemios', id: 'partido_6'},
    },
  fecha_10: {
      nombre: 'Fecha 10',
      partido_1: { equipo_1: 'Capurro', equipo_2: 'Albatros', id: 'partido_1'},
      partido_2: { equipo_1: 'Reducto', equipo_2: 'Yale', id: 'partido_2'},
      partido_3: { equipo_1: 'Auriblanco', equipo_2: 'Marne', id: 'partido_3'},
      partido_4: { equipo_1: 'Layva', equipo_2: 'Montevideo', id: 'partido_4'},
      partido_5: { equipo_1: 'Atenas', equipo_2: 'Welcome', id: 'partido_5'},
      partido_6: { equipo_1: 'Paysandu', equipo_2: 'Juventud', id: 'partido_6'},
    },
  fecha_11: {
      nombre: 'Fecha 11',
      partido_1: { equipo_1: 'Albatros', equipo_2: 'Paysandu', id: 'partido_1'},
      partido_2: { equipo_1: 'Welcome', equipo_2: 'Capurro', id: 'partido_2'},
      partido_3: { equipo_1: 'Montevideo', equipo_2: 'Atenas', id: 'partido_3'},
      partido_4: { equipo_1: 'Marne', equipo_2: 'Layva', id: 'partido_4'},
      partido_5: { equipo_1: 'Yale', equipo_2: 'Auriblanco', id: 'partido_5'},
      partido_6: { equipo_1: 'Bohemios', equipo_2: 'Reducto', id: 'partido_6'},
    },
  fecha_12: {
      nombre: 'Fecha 12',
      partido_1: { equipo_1: 'Juventud', equipo_2: 'Albatros', id: 'partido_1'},
      partido_2: { equipo_1: 'Auriblanco', equipo_2: 'Bohemios', id: 'partido_2'},
      partido_3: { equipo_1: 'Layva', equipo_2: 'Yale', id: 'partido_3'},
      partido_4: { equipo_1: 'Atenas', equipo_2: 'Marne', id: 'partido_4'},
      partido_5: { equipo_1: 'Capurro', equipo_2: 'Montevideo', id: 'partido_5'},
      partido_6: { equipo_1: 'Paysandu', equipo_2: 'Welcome', id: 'partido_6'},
    },
  fecha_13: {
      nombre: 'Fecha 13',
      partido_1: { equipo_1: 'Welcome', equipo_2: 'Juventud', id: 'partido_1'},
      partido_2: { equipo_1: 'Montevideo', equipo_2: 'Paysandu', id: 'partido_2'},
      partido_3: { equipo_1: 'Marne', equipo_2: 'Capurro', id: 'partido_3'},
      partido_4: { equipo_1: 'Yale', equipo_2: 'Atenas', id: 'partido_4'},
      partido_5: { equipo_1: 'Bohemios', equipo_2: 'Layva', id: 'partido_5'},
      partido_6: { equipo_1: 'Reducto', equipo_2: 'Auriblanco', id: 'partido_6'},
    }
  };

export default fechas;