const timesByActivity = {
  femenino: {
    mon: [{start_time: '16:00', end_time: '17:00'}],
    tu: [],
    wed: [{start_time: '17:00', end_time: '18:00'}],
    th: [{start_time: '17:00', end_time: '18:00'}],
    fri: [],
    sat: [],
    sun: [],
  },
  preinfantiles: {
    mon: [{start_time: '17:00', end_time: '18:00'}],
    tu: [{start_time: '17:30', end_time: '18:30'}],
    wed: [],
    th: [],
    fri: [{start_time: '17:00', end_time: '18:00'}],
    sat: [],
    sun: [],
  },
  preminis_y_minis: {
    mon: [{start_time: '18:00', end_time: '19:00'}],
    tu: [],
    wed: [],
    th: [],
    fri: [],
    sat: [],
    sun: [],
  },
  escuelita: {
    mon: [{start_time: '19:00', end_time: '20:00'}],
    tu: [],
    wed: [{start_time: '18:00', end_time: '19:00'}],
    th: [],
    fri: [],
    sat: [],
    sun: [],
  },
  u21: {
    mon: [{start_time: '20:00', end_time: '21:00'}],
    tu: [{start_time: '18:30', end_time: '20:00'}],
    wed: [],
    th: [],
    fri: [{start_time: '19:00', end_time: '20:00'}],
    sat: [],
    sun: [],
  },
  cadetes: {
    mon: [],
    tu: [{start_time: '15:30', end_time: '16:30'}],
    wed: [{start_time: '16:00', end_time: '17:00'}],
    th: [],
    fri: [{start_time: '16:00', end_time: '17:00'}],
    sat: [],
    sun: [],
  },
  infantiles: {
    mon: [],
    tu: [{start_time: '16:30', end_time: '17:30'}],
    wed: [{start_time: '15:00', end_time: '16:00'}],
    th: [],
    fri: [{start_time: '15:00', end_time: '16:00'}],
    sat: [],
    sun: [],
  },
  preminis: {
    mon: [],
    tu: [],
    wed: [{start_time: '19:00', end_time: '20:00'}],
    th: [{start_time: '18:00', end_time: '19:00'}],
    fri: [],
    sat: [],
    sun: [],
  },
  minies: {
    mon: [],
    tu: [],
    wed: [{start_time: '20:00', end_time: '21:00'}],
    th: [{start_time: '19:00', end_time: '20:00'}],
    fri: [],
    sat: [],
    sun: [],
  },
  juveniles: {
    mon: [],
    tu: [{start_time: '18:30', end_time: '20:00'}],
    wed: [],
    th: [{start_time: '16:00', end_time: '17:00'}],
    fri: [{start_time: '18:00', end_time: '19:00'}],
    sat: [],
    sun: [],
  }
}

export default timesByActivity;