const timesByActivity = {
  escuelita: {
    mon: [],
    tu: [{start_time: '19:00', end_time: '20:00'}],
    wed: [],
    th: [{start_time: '19:00', end_time: '20:00'}],
    fri: [],
    sat: [],
    sun: [],
  },
  preminis_1: {
    mon: [],
    tu: [{start_time: '18:00', end_time: '19:00'}],
    wed: [],
    th: [{start_time: '18:00', end_time: '19:00'}],
    fri: [],
    sat: [],
    sun: [],
  },
  preminis_2: {
    mon: [{start_time: '19:00', end_time: '20:00'}],
    tu: [],
    wed: [{start_time: '19:00', end_time: '20:00'}],
    th: [],
    fri: [],
    sat: [],
    sun: [],
  },
  minis: {
    mon: [{start_time: '18:00', end_time: '19:00'}],
    tu: [],
    wed: [{start_time: '18:00', end_time: '19:00'}],
    th: [],
    fri: [{start_time: '18:00', end_time: '19:00'}],
    sat: [],
    sun: [],
  },
  femenino_u12: {
    mon: [],
    tu: [],
    wed: [{start_time: '18:00', end_time: '19:00'}],
    th: [],
    fri: [],
    sat: [],
    sun: [],
  },
  femenino_u14: {
    mon: [],
    tu: [],
    wed: [{start_time: '17:00', end_time: '18:00'}],
    th: [],
    fri: [],
    sat: [],
    sun: [],
  },
  preinfantiles_1: {
    mon: [{start_time: '16:00', end_time: '17:00'}],
    tu: [],
    wed: [{start_time: '17:00', end_time: '18:00'}],
    th: [],
    fri: [{start_time: '17:00', end_time: '18:00'}],
    sat: [],
    sun: [],
  },
  preinfantiles_2: {
    mon: [{start_time: '17:00', end_time: '18:00'}],
    tu: [],
    wed: [{start_time: '17:00', end_time: '18:00'}],
    th: [],
    fri: [{start_time: '17:00', end_time: '18:00'}],
    sat: [],
    sun: [],
  },
  infantiles: {
    mon: [],
    tu: [{start_time: '16:00', end_time: '17:00'}],
    wed: [{start_time: '16:00', end_time: '17:00'}],
    th: [{start_time: '16:00', end_time: '17:00'}],
    fri: [],
    sat: [],
    sun: [],
  },
  cadetes: {
    mon: [],
    tu: [{start_time: '17:00', end_time: '18:00'}],
    wed: [],
    th: [{start_time: '17:00', end_time: '18:00'}],
    fri: [{start_time: '16:00', end_time: '17:00'}],
    sat: [],
    sun: [],
  },
  juveniles: {
    mon: [],
    tu: [{start_time: '20:00', end_time: '21:00'}],
    wed: [{start_time: '20:00', end_time: '21:00'}],
    th: [],
    fri: [{start_time: '19:00', end_time: '20:00'}],
    sat: [],
    sun: [],
  },
  u21: {
    mon: [],
    tu: [{start_time: '20:00', end_time: '21:00'}],
    wed: [],
    th: [{start_time: '18:00', end_time: '19:00'}],
    fri: [],
    sat: [{start_time: '17:00', end_time: '18:00'}],
    sun: [],
  }
}

export default timesByActivity;